### ISSUE TITLE
[BUG]connection fails

### ISSUE THREAD

**Issue by ExplodingHairyPotatoCat** [Lambdagon/tf_coop_lambda#21]
when playing with my friend, we couldn't connect to eachother when one of us was hosting a server. we can invite eachother and "join" but the connection fails after 4 attempts. there's too many of us to provide accurate hardware details, so i can't do that

**Comment by ArgonianGuard** [comment]
Are you using the dev branch and using the Coplay connect/invite through the friends list on the right side, or the Coplay icon at the bottom of the menu?

**Comment by ExplodingHairyPotatoCat** [comment]
I didn't know about the coplay button on the bottom before now, but i was using the menu on the right

**Comment by ExplodingHairyPotatoCat** [comment]
![image](https://github.com/user-attachments/assets/9675a05f-29fd-47db-8371-3f1f6cfb2f33)
I don't think this is supposed to not copy at all

**Comment by ExplodingHairyPotatoCat** [comment]
yeah, tried it and it still doesn't work

**Comment by ExplodingHairyPotatoCat** [comment]
well somethign made it work and i have no idea what

**Comment by ExplodingHairyPotatoCat** [comment]
it was stuck on connecting and no longer works

**Comment by ArgonianGuard** [comment]
Maybe try setting the join filter to Off, then after a few seconds set it back to Friends Only or Anyone. It will close and re-initialize the connection system.

**Comment by ExplodingHairyPotatoCat** [comment]
I'm just a fucking moron. the issue isn't a thing, the only thing is sometimes the ui is buggy but that's not super common, sorry about that.
