### ISSUE TITLE
[FCDownloader Issues] is the downloader still useable?

### ISSUE THREAD

**Issue by ExplodingHairyPotatoCat** [Lambdagon/tf_coop_lambda#25]
I can't find the downloader, is it still downloadable? i wanna update but i don't wanna reinstall the whole thing again

**Comment by blackletum** [comment]
It is unsupported and has been removed.

The next Main update will come with alternative installation methods, but for now, the only supported installation method we have now is via downloading directly from Github through the website or through the Github Desktop application.
