### ISSUE TITLE
Missing snark model? (BUG)

### ISSUE THREAD

**Issue by presario42** [Lambdagon/tf_coop_lambda#27]
## Describe your issue.
```
Apparently snarks don't have a model, and when launched they appear as ERRORs
```

## Screenshots, Video or Dump file
![image](https://github.com/user-attachments/assets/06c3d465-f49b-466f-bbc5-34234d9d733e)

## Desktop (please complete the following information):
```
 OS: Windows 10
 OS version / codename: 22H2
 Installer Utility:
 Game Version: 06/23 (June 2023)
```

## Additional notes
```
Using the latest DEV branch game version
The snarks are from one of the rocket launchers, is this normal behaviour?
```

**Comment by blackletum** [comment]
Half Life Source needs to be installed, as that is where the snark model is pulled from.

**Comment by presario42** [comment]
ooooh

**Comment by blackletum** [comment]
I will bring this up internally, since if we want this weapon to remain in the game, forcing players to install HL:S just for a single model is a bit extreme.
