### ISSUE TITLE
I can't play the game.

### ISSUE THREAD

**Issue by ItzRoss** [Lambdagon/tf_coop_lambda#3]
Every time I download the file and UNZIP it with both 7zip and WinRar, it'll show an error saying "unexpected end of data" I redownloaded it multiple times, no avail. I restarted Steam, nothing. Whenever I launch it, it'll play like normal till it tries to load the main menu, then it crashes with an engine error reading. "Can't open scripts/objects.txt for object info." I've tried going to multiple different places for help but no one knows how to fix it. I haven't been able to play this mod once and it looks really fun.

**Comment by VintageLife420** [comment]
Down

> Every time I download the file and UNZIP it with both 7zip and WinRar, it'll show an error saying "unexpected end of data" I redownloaded it multiple times, no avail. I restarted Steam, nothing. Whenever I launch it, it'll play like normal till it tries to load the main menu, then it crashes with an engine error reading. "Can't open scripts/objects.txt for object info." I've tried going to multiple different places for help but no one knows how to fix it. I haven't been able to play this mod once and it looks really fun.

Download using Github Desktop.

**Comment by AverageMedalEnjoyer** [comment]
And also talk about this issue in the Discord server. Not here.

**Comment by ItzRoss** [comment]
I wasn't in the discord when I first installed, your invitations need to be renewed.
