### ISSUE TITLE
LFCE Beta Downloader icon not showing on specific names

### ISSUE THREAD

**Issue by theanyoneuser** [Lambdagon/tf_coop_lambda#4]
The icon does not show up when it is named "lfce_downloader.exe". When the exe is named "lfce_downloader (1).exe" the icon shows up. 

(I have no idea how to assign a label)

**Comment by practicemedicine** [comment]
I don't know whenever if its the issue with PyInstaller ( a python tool I used to compile LFCEDownloader) whether after compilation it still shows the default PyInstaller icon, when I moved it to a specific random location it shows the default icon. I'll close this issue cause I don't know how to fix this. 

----

(This issue didn't appear on Pre-Milestone 1 aka the old LFCEDownloader)

**Comment by theanyoneuser** [comment]
Damn thats sad :(

**Comment by practicemedicine** [comment]
![image](https://github.com/Lambdagon/tf_coop_lambda/assets/102203580/13c8c3e7-6339-4f2d-8548-4426504f8c88)

Here is the preview on a different Operating System (Windows 8.1), so this could be an issue with the compiler (PyInstaller)?
This is also a dual booted machine, all of my other files could still be accessed on Windows 11 and 8.1

**Comment by VintageLife420** [comment]
It works now tho

**Comment by theanyoneuser** [comment]
Worked after I restarted the computer and stuff, so I am going to close this issue forum
