### ISSUE TITLE
GUI Glitch

### ISSUE THREAD

**Issue by Vladis7685** [Lambdagon/tf_coop_lambda#5]
This glitch makes the map option unselectable
Edit: It is clickable sometimes, so.. not a problem
![wth this is unplayable](https://github.com/Lambdagon/tf_coop_lambda/assets/69388321/1aad4832-ae15-4435-a614-7b05ca46e21b)

**Comment by VintageLife420** [comment]
Do you have TF2 and Source SDK 2013 Base Multiplayer and HL2 installed?

**Comment by Vladis7685** [comment]
> Do you have TF2 and Source SDK 2013 Base Multiplayer and HL2 installed?

Of course I do

**Comment by TwilightBob** [comment]
Do you have tf2 installed?

**Comment by Vladis7685** [comment]
> Do you have tf2 installed?

Yes

**Comment by TwilightBob** [comment]
ok

**Comment by TwilightBob** [comment]
thats wierd

**Comment by TwilightBob** [comment]
wait

**Comment by TwilightBob** [comment]
did you download lfce using github desktop?

**Comment by Vladis7685** [comment]
?

**Comment by Vladis7685** [comment]
yes i did

**Comment by TwilightBob** [comment]
Try redownloading it again?

**Comment by Vladis7685** [comment]
The problem is with GUI being not adapted to my screen ratio bruh

**Comment by Vladis7685** [comment]
Oh nvm i think it fixed itself
I just relaunched LF

**Comment by Vladis7685** [comment]
Now the options are clickable

**Comment by AverageMedalEnjoyer** [comment]
> did you download lfce using github desktop?

we have an auto installer now

**Comment by practicemedicine** [comment]
> > did you download lfce using github desktop?
> 
> we have an auto installer now

don't forget that lfcedownloader is not steamos's automated graphical installer. it doesn't automatically install it when you run the utility instead there some options on where you would install lfce or smth.

**Comment by practicemedicine** [comment]
(i also didnt realized that i didnt confirm this when people calling it auto updater or auto installer)
