### ISSUE TITLE
If you sit in the weapon selection screen in the loadout menu for too long, it locks you in there and doesn't allow you to change weapons for any class anymore. [BUG]

### ISSUE THREAD

**Issue by mcheezic05** [Lambdagon/tf_coop_lambda#6]
## Describe your issue.
```
As the title says, if you sit there for too long, you can't change weapons anymore. It doesn't let you choose a weapon and selecting a different class to modify the loadout doesn't work. Restarting fixes the issue temporarily, but the issue arises again. I've tried re-installing the game and the issue happened again.
```
## Screenshots, Video or Dump file
https://youtu.be/x-Tk6uEs-lc

## Desktop:
```
 OS: Windows 10
 OS version / codename: not known (for windows run "winver")
 Installer Utility: LFCEDownloader
 Game Version: 06/23 (June 2023)
```

## Additional context
```
Seems to only happen if you sit there for a little while, timing seems inconsistent. Only gives you enough time to read the stats of a few weapons.
```

----

PracticeMedicine; This issue also exists on live TF2.
Balimbanana; This might be fixed on the latest loadout, after updating, see if it is still happening.

**Comment by VintageLife420** [comment]
Yeah, this is a problem which barely happens so theres no point in fixing it. This has even happened in Live TF2 once for me

**Comment by mcheezic05** [comment]
That sucks, because this happens almost every time I change my loadout.

**Comment by Balimbanana** [comment]
This might be fixed on the latest loadout, after updating, see if it is still happening.

**Comment by Balimbanana** [comment]
Closing this issue as it has not been reported by anyone since the last loadout patch.
