### ISSUE TITLE
[CRASH] Game wont launch

### ISSUE THREAD

**Issue by RyanDavanzo** [Lambdagon/tf_coop_lambda#7]
I installed it, but then I click to play it on steam, nothing happens. Is there an hidden executable outside steam so i can open it?

**Comment by AverageMedalEnjoyer** [comment]
do you have source sdk 2013 multiplayer?

**Comment by practicemedicine** [comment]
Do you have Source SDK Base 2013 Multiplayer installed?

**Comment by RyanDavanzo** [comment]
yep. Every SDK in fact

**Comment by Balimbanana** [comment]
These are the required games (as of current):
```
Source SDK Base 2013 Multiplayer
Team Fortress 2
Half-Life 2
```
They must all be installed and functional.

**Comment by RyanDavanzo** [comment]
They are.

**Comment by practicemedicine** [comment]
Closing this issue as NO ONE commented on this issue.
