### ISSUE TITLE
[LFCEDownloader Issues] Latest version crashes on Windows 11

### ISSUE THREAD

**Issue by Hedwig7s** [Lambdagon/tf_coop_lambda#8]
## Your issue:
```
*Crashes with error: Failed to extract mingw64\bin\Atlassian.Bitbucket.UI.exe.config: failed to open target file!
fopen: Permission denied*
```

## Your OS & OS version (ex. Arch Linux Rolling, Ubuntu 22.04 Jammy  Jellyfish, HoloISO 4.0 / SteamOS 3.4?, Windows 10 or others.)
```
Windows 11 (NT 10.0)
```

### (The version details are at the very bottom.)
```
No
```

## Have you recently updated your LFCEDownloader client recently?
```
Yes
```

----

# Developer comments
PracticeMedicine; This utility was tested on Windows 10. Windows 11 have the same NT Version as 10, which is "10.0", so the utility should work on Windows 11. This issue is similar to the old issue, this is an issue of extracting the Git binaries 
### PracticeMedicine; This will be investigated tomorrow, do not close this issue

**Comment by practicemedicine** [comment]
Try running it as an administrator.

**Comment by Hedwig7s** [comment]
> Try running it as an administrator.

I did no change

**Comment by practicemedicine** [comment]
> > Try running it as an administrator.
> 
> I did no change

Have you installed it on the release tab? If so, maybe you should try installing it on https://raw.githubusercontent.com/Lambdagon/tf_coop_lambda/main/lfce_downloader.exe

**Comment by Hedwig7s** [comment]
I also tried that and yet again it just threw that again

**Comment by practicemedicine** [comment]
> I also tried that and yet again it just threw that again

I'll investigate tomorrow, this will be tested on 2 virtual machines (Windows 10 and Fedora)

**Comment by practicemedicine** [comment]
Issue closed, in case of the new beta release of FCDownloader.

**Comment by mhpph** [comment]
help
![Uploading 屏幕截图 2024-02-02 182605.png…]()
